ln -s `pwd`/ackrc $HOME/.ackrc
ln -s `pwd`/dircolors $HOME/.dircolors
ln -s `pwd`/gemrc $HOME/.gemrc
ln -s `pwd`/gitconfig $HOME/.gitconfig
ln -s `pwd`/gitignore $HOME/.gitignore
ln -s `pwd`/install.sh $HOME/.install.sh
ln -s `pwd`/irbrc $HOME/.irbrc
ln -s `pwd`/powconfig $HOME/.powconfig
ln -s `pwd`/vim $HOME/.vim
ln -s `pwd`/vimrc $HOME/.vimrc
ln -s `pwd`/zlogin $HOME/.zlogin
ln -s `pwd`/zlogout $HOME/.zlogout
ln -s `pwd`/zpreztorc $HOME/.zpreztorc
ln -s `pwd`/zprofile $HOME/.zprofile
ln -s `pwd`/zshenv $HOME/.zshenv
ln -s `pwd`/zshrc $HOME/.zshrc
ln -s `pwd`/zshrc.local $HOME/.zshrc.local
