ls -s `pwd`/ackrc $HOME/.ackrc
ls -s `pwd`/dircolors $HOME/.dircolors
ls -s `pwd`/gemrc $HOME/.gemrc
ls -s `pwd`/gitconfig $HOME/.gitconfig
ls -s `pwd`/gitignore $HOME/.gitignore
ls -s `pwd`/irbrc $HOME/.irbrc
ls -s `pwd`/powconfig $HOME/.powconfig
ls -s `pwd`/vim $HOME/.vim
ls -s `pwd`/vimrc $HOME/.vimrc
ls -s `pwd`/zlogin $HOME/.zlogin
ls -s `pwd`/zlogout $HOME/.zlogout
ls -s `pwd`/zpreztorc $HOME/.zpreztorc
ls -s `pwd`/zprofile $HOME/.zprofile
ls -s `pwd`/zshenv $HOME/.zshenv
ls -s `pwd`/zshrc $HOME/.zshrc
ls -s `pwd`/zshrc.local $HOME/.zshrc.local
