export EDITOR='nvim'
export VISUAL='view'
export PAGER='less'
export TERM=xterm-256color

source /etc/bashrc

# eval $(dircolors -b ~/.dircolors)
[ -r ~/.aliases.bash ] && source ~/.aliases.bash
[ -r ~/.bash.local ] && source ~/.bash.local
# [ -f /usr/local/share/liquidprompt ] && source /usr/local/share/liquidprompt
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -e ~/.iterm2_shell_integration.bash ] && source ~/.iterm2_shell_integration.bash
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
[ -f ~/.sdkman/bin/sdkman-init.sh ] && source ~/.sdkman/bin/sdkman-init.sh
[ -f /usr/local/opt/asdf/asdf.sh ] && source /usr/local/opt/asdf/asdf.sh

shopt -s cdspell
stty -ixon -igncr

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export HISTSIZE=16384
# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
# After each command, append to the history file and reread it
# export PROMPT_COMMAND="history -a; history -c; history -r"
ulimit -S -n 512

eval "$(stack --bash-completion-script stack)"
