export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR='nvim'
export VISUAL='view'
export PAGER='less'
export TERM=xterm-256color
export DARK_MODE=$(osascript -l JavaScript -e "Application('System Events').appearancePreferences.darkMode()")

echo "Sourcing /etc/bashrc"
source /etc/bashrc

echo "Sourcing aliases"
[ -r ~/.aliases.bash ] && source ~/.aliases.bash

echo "Sourcing local"
[ -r ~/.bash.local ] && source ~/.bash.local

echo "Sourcing fzf"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

echo "Sourcing bash completion"
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

echo "Sourcing asdf"
[ -f /usr/local/opt/asdf/asdf.sh ] && source /usr/local/opt/asdf/asdf.sh

eval "$(direnv hook bash)"

shopt -s cdspell
stty -ixon -igncr

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export HISTSIZE=16384
# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
# After each command, append to the history file and reread it
# export PROMPT_COMMAND="history -a; history -c; history -r"
ulimit -S -n 512

# eval "$(stack --bash-completion-script stack)"
echo "Sourcing nix"
if [ -e /Users/0rca/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/0rca/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

