if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

eval $(dircolors -b $HOME/.dircolors)

[ -r $HOME/.zshrc.local ] && source $HOME/.zshrc.local

shopt -s cdspell

export PATH="$HOME/.rbenv/bin:$PATH"

eval "$(rbenv init - --no-rehash)"
