#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
eval $(dircolors -b $HOME/.dircolors.256dark)

bindkey '^R' history-incremental-search-backward

if [[ -f $HOME/.zshrc.local ]]; then
  source $HOME/.zshrc.local
fi

unsetopt correct
